name: Build For Linux

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deps Installing
      run: |
        sudo apt-get update
        sudo apt-get install cmake gcc@11

    - name: Building From Source
      run: |
      mkdir build && cd build
      cmake ..
      make install